language: node_js
node_js:
  - 11.14.0
dist: xenial
services:
  - xvfb
addons:
  firefox: "latest"

notifications:
  slack: cse112-sp19-team5:cT0qoRmCjVBz1I7ogt2dGG39

env:
  global:
    - CC_TEST_REPORTER_ID=8a52c7f9f5cf5a0f5a87e12df01bb76055af78143883df44798132ad52975c71

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# before_script:
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
#   - sleep 3

before_script:
  - npm install

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - npm run lint
  - npm test
  - npm run browsertest
  - npm run docs

after_success:
  - bash scripts/after_script.sh $TRAVIS_PULL_REQUEST
