language: node_js
node_js:
    - 11.14.0

notifications:
  slack: cse112-sp19-team5:cT0qoRmCjVBz1I7ogt2dGG39

before_install:
  - npm install -g xmlcreate
  - npm install -g eslint eslint-config-google
  - npm install -g jsdoc
  - npm install -g htmllint-cli
  - npm install -g stylelint
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - jsdoc -r . -c jsdoc.json -d docs
  - npx eslint ./**/*.js 
  - htmllint *.html
  - stylelint ./**/*.css
  - node_modules/karma/bin/karma start karma.conf.js --single-run


